environment: lab

location: "East US"

resources:
  resource_group:
    enabled: true
    name: "rg-lab-demo"

  storage_account:
    enabled: true
    name: "labsa001"

  key_vault:
    enabled: true
    name: "lab-kv-testing"
  