environment: live

location: "East US"
resources:
  resource_group:
    enabled: true
    name: "rg-live-demo"

  storage_account:
    enabled: true
    name: "livesa002"

  key_vault:
    enabled: true
    name: "live-kv-testing"
 