environment: non-live

location: "East US"
resources:
  resource_group:
    enabled: true
    name: "rg-non-live-demo"
  storage_account:
    enabled: true
    name: "nonlivesa003"

  key_vault:
    enabled: true
    name: "nonlive-kv-testing"